
import type { NewBusiness } from './data';
import { format, addYears, subYears } from 'date-fns';

const initialActivity = (date: Date) => [
    {
        date: date.toISOString(),
        user: 'Sales Agent',
        action: 'Policy Created',
        details: 'Initial policy creation.'
    },
    {
        date: date.toISOString(),
        user: 'System',
        action: 'Status changed to Pending First Premium'
    }
];

export const seedPoliciesData: Omit<NewBusiness, 'id'>[] = [
  // 5 Issued Policies from the past
  {
    client: "Mrs. Evelyn Mensah",
    lifeAssuredDob: "1985-02-18",
    placeOfBirth: "Ho",
    ageNextBirthday: 40,
    gender: "Female",
    maritalStatus: "Married",
    dependents: 1,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Ewe",
    email: "evelyn.mensah@example.com",
    phone: "0245678123",
    postalAddress: "P.O. Box VH 200, Ho",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-111222333-5",
    placeOfIssue: "NIA, Ho",
    issueDate: "2020-02-28",
    expiryDateId: "2030-02-27",
    policy: "T1166017",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 300,
    initialSumAssured: 150000,
    sumAssured: 150000,
    commencementDate: subYears(new Date(), 2).toISOString(),
    expiryDate: addYears(subYears(new Date(), 2), 35).toISOString(),
    policyTerm: 35,
    premiumTerm: 25,
    serial: "1010",
    paymentFrequency: "Monthly",
    onboardingStatus: "Policy Issued",
    billingStatus: "Up to Date",
    policyStatus: "Active",
    mandateVerified: true,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: true, completed: true },
    bills: [], // Simplified for seeding
    payments: [], // Simplified for seeding
    activityLog: [], // Simplified for seeding
    primaryBeneficiaries: [{ name: "Frank Mensah", dob: "1980-10-10", gender: "Male", relationship: "Spouse", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Absa Bank Ghana Limited",
    bankBranch: "Ho",
    payerName: "Evelyn Mensah",
    bankAccountNumber: "1050098765432",
    sortCode: "240801",
    narration: "AUG 2024 PREMIUM",
    accountType: "Savings",
    bankAccountName: "Evelyn Mensah",
    amountInWords: "Three Hundred Ghana Cedis",
    occupation: "Nurse",
    natureOfBusiness: "Healthcare",
    employer: "Ho Teaching Hospital",
    employerAddress: "Ho, Volta Region",
    monthlyBasicIncome: 3000,
    otherIncome: 200,
    totalMonthlyIncome: 3200,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Mr. Samuel Cudjoe",
    lifeAssuredDob: "1986-07-07",
    placeOfBirth: "Axim",
    ageNextBirthday: 39,
    gender: "Male",
    maritalStatus: "Married",
    dependents: 1,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Nzema",
    email: "samuel.cudjoe@example.com",
    phone: "0200555666",
    postalAddress: "P.O. Box AX 77, Axim",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-121212121-9",
    placeOfIssue: "NIA, Axim",
    issueDate: "2021-01-01",
    expiryDateId: "2030-12-31",
    policy: "T1166018",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 420,
    initialSumAssured: 210000,
    sumAssured: 210000,
    commencementDate: subYears(new Date(), 3).toISOString(),
    expiryDate: addYears(subYears(new Date(), 3), 36).toISOString(),
    policyTerm: 36,
    premiumTerm: 26,
    serial: "1015",
    paymentFrequency: "Monthly",
    onboardingStatus: "Policy Issued",
    billingStatus: "Outstanding",
    policyStatus: "Active",
    mandateVerified: true,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: true, completed: true },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Mary Cudjoe", dob: "1990-01-01", gender: "Female", relationship: "Spouse", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Absa Bank Ghana Limited",
    bankBranch: "Axim",
    payerName: "Samuel Cudjoe",
    bankAccountNumber: "4455667788990",
    sortCode: "042201",
    narration: "AUG 2024 PREMIUM",
    accountType: "Savings",
    bankAccountName: "Samuel Cudjoe",
    amountInWords: "Four Hundred and Twenty Ghana Cedis",
    occupation: "Fisherman",
    natureOfBusiness: "Fishing",
    employer: "Self-Employed",
    employerAddress: "Axim Harbour",
    monthlyBasicIncome: 3000,
    otherIncome: 1000,
    totalMonthlyIncome: 4000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Ms. Sandra Owusu",
    lifeAssuredDob: "1983-08-08",
    placeOfBirth: "Takoradi",
    ageNextBirthday: 42,
    gender: "Female",
    maritalStatus: "Divorced",
    dependents: 2,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Fante",
    email: "sandra.owusu@example.com",
    phone: "0209871234",
    postalAddress: "P.O. Box TD 500, Takoradi",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-777888999-7",
    placeOfIssue: "NIA, Takoradi",
    issueDate: "2019-12-10",
    expiryDateId: "2029-12-09",
    policy: "E1274718",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 600,
    initialSumAssured: 300000,
    sumAssured: 300000,
    commencementDate: subYears(new Date(), 1).toISOString(),
    expiryDate: addYears(subYears(new Date(), 1), 33).toISOString(),
    policyTerm: 33,
    premiumTerm: 23,
    serial: "1012",
    paymentFrequency: "Monthly",
    onboardingStatus: "Policy Issued",
    billingStatus: "Up to Date",
    policyStatus: "Active",
    mandateVerified: true,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: true, completed: true },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Junior Owusu", dob: "2010-10-10", gender: "Male", relationship: "Son", percentage: 50 }, { name: "Adjoa Owusu", dob: "2012-12-12", gender: "Female", relationship: "Daughter", percentage: 50 }],
    contingentBeneficiaries: [],
    bankName: "Ecobank Ghana PLC",
    bankBranch: "Takoradi",
    payerName: "Sandra Owusu",
    bankAccountNumber: "9040001122334",
    sortCode: "301101",
    narration: "AUG 2024 PREMIUM",
    accountType: "Current",
    bankAccountName: "Sandra Owusu",
    amountInWords: "Six Hundred Ghana Cedis",
    occupation: "Lawyer",
    natureOfBusiness: "Legal",
    employer: "Owusu & Associates",
    employerAddress: "Liberation Road, Takoradi",
    monthlyBasicIncome: 10000,
    otherIncome: 2000,
    totalMonthlyIncome: 12000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Dr. Charles Ofori",
    lifeAssuredDob: "1975-04-22",
    placeOfBirth: "Accra",
    ageNextBirthday: 50,
    gender: "Male",
    maritalStatus: "Married",
    dependents: 4,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English",
    email: "charles.ofori@example.com",
    phone: "0201122334",
    postalAddress: "P.O. Box LG 1, Legon",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-555444333-2",
    placeOfIssue: "NIA, Accra",
    issueDate: "2019-08-10",
    expiryDateId: "2029-08-09",
    policy: "T1166019",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 1000,
    initialSumAssured: 500000,
    sumAssured: 500000,
    commencementDate: subYears(new Date(), 4).toISOString(),
    expiryDate: addYears(subYears(new Date(), 4), 25).toISOString(),
    policyTerm: 25,
    premiumTerm: 15,
    serial: "1005",
    paymentFrequency: "Monthly",
    onboardingStatus: "Policy Issued",
    billingStatus: "Up to Date",
    policyStatus: "Active",
    mandateVerified: true,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: true, completed: true },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Beatrice Ofori", dob: "1978-12-01", gender: "Female", relationship: "Spouse", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Ecobank Ghana PLC",
    bankBranch: "Legon",
    payerName: "Charles Ofori",
    bankAccountNumber: "1050012345678",
    sortCode: "240105",
    narration: "AUG 2024 PREMIUM",
    accountType: "Current",
    bankAccountName: "Dr. Charles Ofori",
    amountInWords: "One Thousand Ghana Cedis",
    occupation: "Doctor",
    natureOfBusiness: "Healthcare",
    employer: "Korle Bu Teaching Hospital",
    employerAddress: "Korle Bu, Accra",
    monthlyBasicIncome: 12000,
    otherIncome: 3000,
    totalMonthlyIncome: 15000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Mr. Femi Adebayo",
    lifeAssuredDob: "1978-06-25",
    placeOfBirth: "Ibadan",
    ageNextBirthday: 47,
    gender: "Male",
    maritalStatus: "Married",
    dependents: 3,
    nationality: "Nigerian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Yoruba",
    email: "femi.adebayo@example.com",
    phone: "0235001122",
    postalAddress: "P.O. Box AD 45, Adabraka, Accra",
    nationalIdType: "Passport",
    idNumber: "NGA7654321",
    placeOfIssue: "Nigerian High Commission",
    issueDate: "2022-08-11",
    expiryDateId: "2027-08-10",
    policy: "E1274719",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 700,
    initialSumAssured: 350000,
    sumAssured: 350000,
    commencementDate: subYears(new Date(), 1).toISOString(),
    expiryDate: addYears(subYears(new Date(), 1), 28).toISOString(),
    policyTerm: 28,
    premiumTerm: 18,
    serial: "1009",
    paymentFrequency: "Monthly",
    onboardingStatus: "Policy Issued",
    billingStatus: "Outstanding",
    policyStatus: "Active",
    mandateVerified: true,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: true, completed: true },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Sade Adebayo", dob: "1982-01-20", gender: "Female", relationship: "Spouse", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Absa Bank Ghana Limited",
    bankBranch: "Head Office",
    payerName: "Femi Adebayo",
    bankAccountNumber: "0010100987654",
    sortCode: "280101",
    narration: "AUG 2024 PREMIUM",
    accountType: "Current",
    bankAccountName: "Femi Adebayo",
    amountInWords: "Seven Hundred Ghana Cedis",
    occupation: "Banker",
    natureOfBusiness: "Finance",
    employer: "Access Bank (Ghana) Plc",
    employerAddress: "Starlets 91 Road, Accra",
    monthlyBasicIncome: 9000,
    otherIncome: 1000,
    totalMonthlyIncome: 10000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },

  // 5 Policies in Onboarding
  {
    client: "Ms. Akua Boahen",
    lifeAssuredDob: "1992-12-01",
    placeOfBirth: "Sunyani",
    ageNextBirthday: 32,
    gender: "Female",
    maritalStatus: "Single",
    dependents: 0,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Bono",
    email: "akua.boahen@example.com",
    phone: "0501239876",
    postalAddress: "P.O. Box SY50, Sunyani",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-321654987-4",
    placeOfIssue: "NIA, Sunyani",
    issueDate: "2021-09-01",
    expiryDateId: "2031-08-31",
    policy: "",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 250,
    initialSumAssured: 125000,
    sumAssured: 125000,
    commencementDate: new Date().toISOString(),
    expiryDate: addYears(new Date(), 43).toISOString(),
    policyTerm: 43,
    premiumTerm: 33,
    serial: "1008",
    paymentFrequency: "Monthly",
    onboardingStatus: "Pending First Premium",
    billingStatus: "Outstanding",
    policyStatus: "Inactive",
    mandateVerified: false,
    firstPremiumPaid: false,
    medicalUnderwritingState: { started: false, completed: false },
    bills: [],
    payments: [],
    activityLog: initialActivity(new Date()),
    primaryBeneficiaries: [{ name: "Kwame Boahen", dob: "1960-01-01", gender: "Male", relationship: "Father", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Ecobank Ghana PLC",
    bankBranch: "Sunyani",
    payerName: "Akua Boahen",
    bankAccountNumber: "9040007654321",
    sortCode: "300801",
    narration: "AUG 2024 PREMIUM",
    accountType: "Savings",
    bankAccountName: "Akua Boahen",
    amountInWords: "Two Hundred and Fifty Ghana Cedis",
    occupation: "Journalist",
    natureOfBusiness: "Media",
    employer: "Multimedia Group",
    employerAddress: "Faanofa Road, Accra",
    monthlyBasicIncome: 3500,
    otherIncome: 500,
    totalMonthlyIncome: 4000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Mr. Richard Peprah",
    lifeAssuredDob: "1998-11-20",
    placeOfBirth: "Obuasi",
    ageNextBirthday: 26,
    gender: "Male",
    maritalStatus: "Single",
    dependents: 0,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Twi",
    email: "richard.peprah@example.com",
    phone: "0557891234",
    postalAddress: "P.O. Box OB 10, Obuasi",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-998877665-6",
    placeOfIssue: "NIA, Obuasi",
    issueDate: "2022-04-15",
    expiryDateId: "2032-04-14",
    policy: "",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 150,
    initialSumAssured: 75000,
    sumAssured: 75000,
    commencementDate: new Date().toISOString(),
    expiryDate: addYears(new Date(), 49).toISOString(),
    policyTerm: 49,
    premiumTerm: 39,
    serial: "1011",
    paymentFrequency: "Monthly",
    onboardingStatus: "First Premium Confirmed",
    billingStatus: "First Premium Paid",
    policyStatus: "Inactive",
    mandateVerified: false,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: false, completed: false },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Abena Peprah", dob: "1975-01-01", gender: "Female", relationship: "Mother", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Ecobank Ghana PLC",
    bankBranch: "Obuasi",
    payerName: "Richard Peprah",
    bankAccountNumber: "3344556677889",
    sortCode: "041201",
    narration: "AUG 2024 PREMIUM",
    accountType: "Savings",
    bankAccountName: "Richard Peprah",
    amountInWords: "One Hundred and Fifty Ghana Cedis",
    occupation: "Mining Engineer",
    natureOfBusiness: "Mining",
    employer: "AngloGold Ashanti",
    employerAddress: "Obuasi Gold Mine, Obuasi",
    monthlyBasicIncome: 5500,
    otherIncome: 0,
    totalMonthlyIncome: 5500,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Mr. Ahmed Bello",
    lifeAssuredDob: "1993-04-14",
    placeOfBirth: "Kano",
    ageNextBirthday: 32,
    gender: "Male",
    maritalStatus: "Single",
    dependents: 0,
    nationality: "Nigerian",
    country: "Ghana",
    religion: "Muslim",
    languages: "English, Hausa",
    email: "ahmed.bello@example.com",
    phone: "0531234567",
    postalAddress: "P.O. Box AC 99, Accra",
    nationalIdType: "Passport",
    idNumber: "NGA987654",
    placeOfIssue: "Nigerian High Commission",
    issueDate: "2023-05-01",
    expiryDateId: "2028-04-30",
    policy: "",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 350,
    initialSumAssured: 180000,
    sumAssured: 180000,
    commencementDate: new Date().toISOString(),
    expiryDate: addYears(new Date(), 43).toISOString(),
    policyTerm: 43,
    premiumTerm: 33,
    serial: "1013",
    paymentFrequency: "Monthly",
    onboardingStatus: "Pending Vetting",
    billingStatus: "First Premium Paid",
    policyStatus: "Inactive",
    mandateVerified: false,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: false, completed: false },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Aisha Bello", dob: "1995-01-01", gender: "Female", relationship: "Sister", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Absa Bank Ghana Limited",
    bankBranch: "Ridge Towers",
    payerName: "Ahmed Bello",
    bankAccountNumber: "1050023456789",
    sortCode: "240101",
    narration: "AUG 2024 PREMIUM",
    accountType: "Current",
    bankAccountName: "Ahmed Bello",
    amountInWords: "Three Hundred and Fifty Ghana Cedis",
    occupation: "IT Consultant",
    natureOfBusiness: "Technology",
    employer: "Self-Employed",
    employerAddress: "Home Office",
    monthlyBasicIncome: 7000,
    otherIncome: 0,
    totalMonthlyIncome: 7000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Ms. Brenda Tetteh",
    lifeAssuredDob: "1979-09-09",
    placeOfBirth: "Somanya",
    ageNextBirthday: 45,
    gender: "Female",
    maritalStatus: "Widowed",
    dependents: 2,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Krobo",
    email: "brenda.tetteh@example.com",
    phone: "0281234500",
    postalAddress: "P.O. Box SA 12, Somanya",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-444555666-8",
    placeOfIssue: "NIA, Somanya",
    issueDate: "2020-10-10",
    expiryDateId: "2030-10-09",
    policy: "",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 550,
    initialSumAssured: 275000,
    sumAssured: 275000,
    commencementDate: new Date().toISOString(),
    expiryDate: addYears(new Date(), 30).toISOString(),
    policyTerm: 30,
    premiumTerm: 20,
    serial: "1014",
    paymentFrequency: "Monthly",
    onboardingStatus: "Pending Mandate",
    billingStatus: "Up to Date",
    policyStatus: "Inactive",
    mandateVerified: false,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: true, completed: true },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Mawuena Tetteh", dob: "2005-01-20", gender: "Female", relationship: "Daughter", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Absa Bank Ghana Limited",
    bankBranch: "Somanya",
    payerName: "Brenda Tetteh",
    bankAccountNumber: "0210100987123",
    sortCode: "280115",
    narration: "AUG 2024 PREMIUM",
    accountType: "Current",
    bankAccountName: "Brenda Tetteh",
    amountInWords: "Five Hundred and Fifty Ghana Cedis",
    occupation: "Business Owner",
    natureOfBusiness: "Retail - Boutique",
    employer: "Brenda's Fashions",
    employerAddress: "Main Street, Somanya",
    monthlyBasicIncome: 8000,
    otherIncome: 0,
    totalMonthlyIncome: 8000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
  {
    client: "Mr. Emmanuel Agyei",
    lifeAssuredDob: "1980-03-12",
    placeOfBirth: "Koforidua",
    ageNextBirthday: 45,
    gender: "Male",
    maritalStatus: "Married",
    dependents: 2,
    nationality: "Ghanaian",
    country: "Ghana",
    religion: "Christian",
    languages: "English, Twi",
    email: "emmanuel.agyei@example.com",
    phone: "0264123789",
    postalAddress: "P.O. Box KF123, Koforidua",
    nationalIdType: "Ghana Card",
    idNumber: "GHA-789123456-3",
    placeOfIssue: "NIA, Koforidua",
    issueDate: "2020-05-20",
    expiryDateId: "2030-05-19",
    policy: "",
    product: "Buy Term and Invest in Mutual Fund",
    premium: 450,
    initialSumAssured: 220000,
    sumAssured: 220000,
    commencementDate: new Date().toISOString(),
    expiryDate: addYears(new Date(), 30).toISOString(),
    policyTerm: 30,
    premiumTerm: 20,
    serial: "1007",
    paymentFrequency: "Monthly",
    onboardingStatus: "Vetting Completed",
    billingStatus: "First Premium Paid",
    policyStatus: "Inactive",
    mandateVerified: false,
    firstPremiumPaid: true,
    medicalUnderwritingState: { started: false, completed: false },
    bills: [],
    payments: [],
    activityLog: [],
    primaryBeneficiaries: [{ name: "Linda Agyei", dob: "1985-08-01", gender: "Female", relationship: "Spouse", percentage: 100 }],
    contingentBeneficiaries: [],
    bankName: "Ecobank Ghana PLC",
    bankBranch: "Koforidua Main",
    payerName: "Emmanuel Agyei",
    bankAccountNumber: "2233445566778",
    sortCode: "040701",
    narration: "AUG 2024 PREMIUM",
    accountType: "Current",
    bankAccountName: "Emmanuel Agyei",
    amountInWords: "Four Hundred and Fifty Ghana Cedis",
    occupation: "Civil Engineer",
    natureOfBusiness: "Construction",
    employer: "Ghana Highway Authority",
    employerAddress: "Pension Drive, Accra",
    monthlyBasicIncome: 6000,
    otherIncome: 2000,
    totalMonthlyIncome: 8000,
    existingPoliciesDetails: [],
    declinedPolicyDetails: [],
    medicalHistory: [],
    familyMedicalHistory: 'no',
    familyMedicalHistoryDetails: [],
    lifestyleDetails: [],
  },
];

  